server.port=${PORT:8080}
spring.application.name=demo

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/fraudwatch?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:mysql}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
